Files = 
{
	"Assets/default.png",
	
	--MenuScene
	"Assets/UI/joystix_monospace.ttf",	--font
	"Assets/UI/UIBackGround.png",
	
	--LocalScene Textures
	"Assets/UI/NorthIcon.png",
	
	"Assets/Isometric/Block/b_dirt_01.png",
	"Assets/Isometric/Block/b_dirt_02.png",
	"Assets/Isometric/Block/b_dirt_03.png",
	"Assets/Isometric/Block/b_dirt_04.png",
	"Assets/Isometric/Block/b_dirt_05.png",
	"Assets/Isometric/Block/b_dirt_06.png",
	"Assets/Isometric/Block/b_dirt_07.png",
	"Assets/Isometric/Block/b_dirt_08.png",
	"Assets/Isometric/Block/b_dirt_09.png",
	
	"Assets/Isometric/Block/b_ice_01.png",
	"Assets/Isometric/Block/b_ice_02.png",
	"Assets/Isometric/Block/b_ice_03.png",
	"Assets/Isometric/Block/b_ice_04.png",
	"Assets/Isometric/Block/b_ice_05.png",
	"Assets/Isometric/Block/b_ice_06.png",
	"Assets/Isometric/Block/b_ice_07.png",
	"Assets/Isometric/Block/b_ice_08.png",
	"Assets/Isometric/Block/b_ice_09.png",

	"Assets/Isometric/Block/b_rock_01.png",
	"Assets/Isometric/Block/b_rock_02.png",
	"Assets/Isometric/Block/b_rock_03.png",
	"Assets/Isometric/Block/b_rock_04.png",
	"Assets/Isometric/Block/b_rock_05.png",
	"Assets/Isometric/Block/b_rock_06.png",
	"Assets/Isometric/Block/b_rock_07.png",
	"Assets/Isometric/Block/b_rock_08.png",
	"Assets/Isometric/Block/b_rock_09.png",
	
	"Assets/Isometric/Block/b_sand_01.png",
	"Assets/Isometric/Block/b_sand_02.png",
	"Assets/Isometric/Block/b_sand_03.png",
	"Assets/Isometric/Block/b_sand_04.png",
	"Assets/Isometric/Block/b_sand_05.png",
	"Assets/Isometric/Block/b_sand_06.png",
	"Assets/Isometric/Block/b_sand_07.png",
	"Assets/Isometric/Block/b_sand_08.png",
	"Assets/Isometric/Block/b_sand_09.png",
	
	"Assets/Isometric/Block/b_water_01.png",
	"Assets/Isometric/Block/b_water_02.png",
	"Assets/Isometric/Block/b_water_03.png",
	"Assets/Isometric/Block/b_water_04.png",
	"Assets/Isometric/Block/b_water_05.png",
	"Assets/Isometric/Block/b_water_06.png",
	"Assets/Isometric/Block/b_water_07.png",
	"Assets/Isometric/Block/b_water_08.png",
	"Assets/Isometric/Block/b_water_09.png",
	
	"Assets/Isometric/Surface/s_debug_00.png",
	"Assets/Isometric/Surface/s_debug_01.png",
	"Assets/Isometric/Surface/s_debug_02.png",
	"Assets/Isometric/Surface/s_debug_03.png",
	"Assets/Isometric/Surface/s_debug_04.png",
	"Assets/Isometric/Surface/s_debug_05.png",
	"Assets/Isometric/Surface/s_debug_06.png",
	"Assets/Isometric/Surface/s_debug_07.png",
	"Assets/Isometric/Surface/s_debug_08.png",
	"Assets/Isometric/Surface/s_debug_09.png",

	"Assets/Isometric/Surface/s_grass_01.png",
	"Assets/Isometric/Surface/s_grass_02.png",
	"Assets/Isometric/Surface/s_grass_03.png",
	"Assets/Isometric/Surface/s_grass_04.png",
	"Assets/Isometric/Surface/s_grass_05.png",
	"Assets/Isometric/Surface/s_grass_06.png",
	"Assets/Isometric/Surface/s_grass_07.png",
	"Assets/Isometric/Surface/s_grass_08.png",
	"Assets/Isometric/Surface/s_grass_09.png",
	
	"Assets/Isometric/Surface/s_snow_01.png",
	"Assets/Isometric/Surface/s_snow_02.png",
	"Assets/Isometric/Surface/s_snow_03.png",
	"Assets/Isometric/Surface/s_snow_04.png",
	"Assets/Isometric/Surface/s_snow_05.png",
	"Assets/Isometric/Surface/s_snow_06.png",
	"Assets/Isometric/Surface/s_snow_07.png",
	"Assets/Isometric/Surface/s_snow_08.png",
	"Assets/Isometric/Surface/s_snow_09.png",
	
	"Assets/Isometric/Surface/s_forest_01.png",
	"Assets/Isometric/Surface/s_forest_02.png",
	"Assets/Isometric/Surface/s_forest_03.png",
	"Assets/Isometric/Surface/s_forest_04.png",
	"Assets/Isometric/Surface/s_forest_05.png",
	"Assets/Isometric/Surface/s_forest_06.png",
	"Assets/Isometric/Surface/s_forest_07.png",
	"Assets/Isometric/Surface/s_forest_08.png",
	"Assets/Isometric/Surface/s_forest_09.png",
	
	"Assets/Isometric/Surface/s_water_01.png",
	"Assets/Isometric/Surface/s_water_02.png",
	"Assets/Isometric/Surface/s_water_03.png",
	"Assets/Isometric/Surface/s_water_04.png",
	"Assets/Isometric/Surface/s_water_05.png",
	"Assets/Isometric/Surface/s_water_06.png",
	"Assets/Isometric/Surface/s_water_07.png",
	"Assets/Isometric/Surface/s_water_08.png",
	"Assets/Isometric/Surface/s_water_09.png",
	
	"Assets/Isometric/Surface/s_ice_01.png",
	"Assets/Isometric/Surface/s_ice_02.png",
	"Assets/Isometric/Surface/s_ice_03.png",
	"Assets/Isometric/Surface/s_ice_04.png",
	"Assets/Isometric/Surface/s_ice_05.png",
	"Assets/Isometric/Surface/s_ice_06.png",
	"Assets/Isometric/Surface/s_ice_07.png",
	"Assets/Isometric/Surface/s_ice_08.png",
	"Assets/Isometric/Surface/s_ice_09.png",
	
	"Assets/Isometric/Element/e_grass.png",
	"Assets/Isometric/Element/e_tallGrass.png",
	"Assets/Isometric/Element/e_snowGrass.png",
	"Assets/Isometric/Element/e_dryGrass.png",
	"Assets/Isometric/Element/e_forestGrass.png",
	"Assets/Isometric/Element/e_tundraGrass.png",
	
	"Assets/Isometric/Element/e_tree.png",
	"Assets/Isometric/Element/e_cactusTree.png",
	"Assets/Isometric/Element/e_yellowTree.png",
	"Assets/Isometric/Element/e_firTree.png",
	"Assets/Isometric/Element/e_tropicalTree.png",
	"Assets/Isometric/Element/e_northTree.png",
	
	"Assets/Isometric/Element/e_house_01.png",
	"Assets/Isometric/Element/e_house_02.png",
	
	"Assets/Isometric/Surface/s_townRoad.png",
	"Assets/Isometric/Surface/s_worldRoad.png",
	
	"Assets/Isometric/Critter/c_player.png",
	"Assets/Isometric/Critter/c_01.png",
	"Assets/Isometric/Critter/c_02.png",
	"Assets/Isometric/Critter/c_03.png",

	"Assets/Critter/01.png",
	"Assets/Critter/02.png",
	"Assets/Critter/03.png",
}